var DB = {
    users: [
        {
            user_id: 100,
            credentials: 0,
            password: "password",
            username: "manager",
            first_name: "Manager",
            last_name: "Test-User",
            email: "manager.test@it.uu.se",
            phone: "",
        },
        {
            user_id: 101,
            credentials: 1,
            password: "password",
            username: "bartender",
            first_name: "Bartender",
            last_name: "Test-User",
            email: "bartender.test@it.uu.se",
            phone: "",
        },
        {
            user_id: 102,
            credentials: 3,
            password: "password",
            username: "vip",
            first_name: "VIP",
            last_name: "Test-User",
            email: "vip.test@it.uu.se",
            phone: "",
        },
        {
            user_id: 2,
            credentials: 0,
            password: "b690bc2447d40ea8a6f78345eb979a28",
            username: "jorass",
            first_name: "Jory",
            last_name: "Assies",
            email: "jory.assies@it.uu.se",
            phone: "0704811411",
        },
        {
            user_id: 28,
            credentials: 3,
            password: "b612f428e4a53386fdb98f6c2164c16c",
            username: "sulstr",
            first_name: "Sulayman",
            last_name: "Street",
            email: "sulayman.street@it.uu.se",
            phone: "0701517627",
        },
        {
            user_id: 27,
            credentials: 3,
            password: "c0d9251f9af5e7410c6a3932f696c449",
            username: "orapan",
            first_name: "Orabela",
            last_name: "Panders",
            email: "orabela.panders@it.uu.se",
            phone: "0701503294",
        },
        {
            user_id: 26,
            credentials: 3,
            password: "4ec434994decffa3005b477cc7f992e6",
            username: "kenolg",
            first_name: "Kenan",
            last_name: "Olguin",
            email: "kenan.olguin@it.uu.se",
            phone: "0706569560",
        },
        {
            user_id: 25,
            credentials: 1,
            password: "971299fa95fe467db26e8bf01864d48d",
            username: "saskru",
            first_name: "Sa\u0161a",
            last_name: "Kr\u00fcger",
            email: "sasa.kruger@it.uu.se",
            phone: "0705349276",
        },
        {
            user_id: 24,
            credentials: 1,
            password: "2a3db2cc165057da53ef13a348e9787f",
            username: "ervtod",
            first_name: "Ervin",
            last_name: "Todd",
            email: "ervin.todd@it.uu.se",
            phone: "0702339018",
        },
        {
            user_id: 23,
            credentials: 3,
            password: "743444f0ff666f1f90580e7bc3af5099",
            username: "aqulyn",
            first_name: "Aquilina",
            last_name: "Lyndon",
            email: "aquilina.lyndon@it.uu.se",
            phone: "0702611287",
        },
        {
            user_id: 22,
            credentials: 3,
            password: "fc4fd22287923f3b47b91fc5f0a85af5",
            username: "lasnic",
            first_name: "Lasse",
            last_name: "Nicholson",
            email: "lasse.nicholson@it.uu.se",
            phone: "0703238992",
        },
        {
            user_id: 21,
            credentials: 3,
            password: "849d51ea793c93194952478aa85694af",
            username: "maihon",
            first_name: "Maiken",
            last_name: "Honda",
            email: "maiken.honda@it.uu.se",
            phone: "0709533955",
        },
        {
            user_id: 20,
            credentials: 2,
            password: "739d0d428ff99dc043e8955b5a4885bc",
            username: "hirchr",
            first_name: "Hiram",
            last_name: "Christopherson",
            email: "hiram.christopherson@it.uu.se",
            phone: "0709599269",
        },
        {
            user_id: 19,
            credentials: 3,
            password: "7e3f6af9d6c2385a79b49b03e87234e5",
            username: "larsch",
            first_name: "Lara",
            last_name: "Schenck",
            email: "lara.schenck@it.uu.se",
            phone: "0702721289",
        },
        {
            user_id: 18,
            credentials: 3,
            password: "1db930e727e73c027fc58b5554935be8",
            username: "janhei",
            first_name: "Jancsi",
            last_name: "Heiman",
            email: "jancsi.heiman@it.uu.se",
            phone: "0707977965",
        },
        {
            user_id: 17,
            credentials: 2,
            password: "f3e3fbabe1b745defda645e5d85a6ac7",
            username: "svetor",
            first_name: "Svetlana",
            last_name: "Torres",
            email: "svetlana.torres@it.uu.se",
            phone: "0707459505",
        },
        {
            user_id: 16,
            credentials: 3,
            password: "75f589d96b212b65298b31717a2641c9",
            username: "pomgra",
            first_name: "Pompeius",
            last_name: "Graner",
            email: "pompeius.graner@it.uu.se",
            phone: "0701584121",
        },
        {
            user_id: 29,
            credentials: 3,
            password: "9e44cc19b9f726583ccc93fa7908f7fd",
            username: "valpag",
            first_name: "Valeria",
            last_name: "Pagani",
            email: "valeria.pagani@it.uu.se",
            phone: "0703156441",
        },
        {
            user_id: 30,
            credentials: 3,
            password: "0f1903b5119eadb705ddba7f2750792f",
            username: "domolh",
            first_name: "Domen",
            last_name: "Olhouser",
            email: "domen.olhouser@it.uu.se",
            phone: "0702459084",
        },
        {
            user_id: 31,
            credentials: 3,
            password: "3fb65e8d64eb23e63c71a86ea97951e0",
            username: "gollan",
            first_name: "Golnar",
            last_name: "Langley",
            email: "golnar.langley@it.uu.se",
            phone: "0702677189",
        },
        {
            user_id: 32,
            credentials: 3,
            password: "3c244190040aedd134913562509a5ea0",
            username: "hyrlap",
            first_name: "Hyram",
            last_name: "Lapointe",
            email: "hyram.lapointe@it.uu.se",
            phone: "0702177650",
        },
        {
            user_id: 33,
            credentials: 3,
            password: "84db5f68a5f2ad3f25bb4445148f434c",
            username: "katfab",
            first_name: "Katrien",
            last_name: "Fabre",
            email: "katrien.fabre@it.uu.se",
            phone: "0705701344",
        },
        {
            user_id: 34,
            credentials: 3,
            password: "edc2623f10cd4d069e710653f3fc630c",
            username: "sulpen",
            first_name: "Sulis\u0142aw",
            last_name: "Pender",
            email: "sulis\u0142aw.pender@it.uu.se",
            phone: "0709481365",
        },
    ],
    account: [
        {
            user_id: 28,
            creditSEK: 450,
        },
        {
            user_id: 27,
            creditSEK: 400,
        },
        {
            user_id: 26,
            creditSEK: 5000,
        },
        {
            user_id: 23,
            creditSEK: 450,
        },
        {
            user_id: 22,
            creditSEK: 650,
        },
        {
            user_id: 21,
            creditSEK: 490,
        },
        {
            user_id: 19,
            creditSEK: 850,
        },
        {
            user_id: 18,
            creditSEK: 1050,
        },
        {
            user_id: 16,
            creditSEK: 850,
        },
        {
            user_id: 29,
            creditSEK: 480,
        },
        {
            user_id: 30,
            creditSEK: 900,
        },
        {
            user_id: 31,
            creditSEK: 0,
        },
        {
            user_id: 32,
            creditSEK: 900,
        },
        {
            user_id: 33,
            creditSEK: 400,
        },
        {
            user_id: 34,
            creditSEK: 1000,
        },
        {
            user_id: 102,
            creditSEK: 999,
        },
    ],
    orders: [
        {
            id: 1,
            table: 6,
            items: [
                {
                    id: 1,
                    beverageNr: "120003",
                    productOnTheHouse: false,
                },
            ],
            notes: "",
            inventory: "barInventory",
            done: false,
            billId: 1,
        },
        {
            id: 2,
            table: 3,
            items: [
                {
                    id: 1,
                    beverageNr: "120003",
                    productOnTheHouse: false,
                },
                {
                    id: 2,
                    beverageNr: "120003",
                    productOnTheHouse: false,
                },
                {
                    id: 3,
                    beverageNr: "1202501",
                    productOnTheHouse: false,
                },
                {
                    id: 4,
                    beverageNr: "8507802",
                    productOnTheHouse: false,
                },
            ],
            notes: "",
            inventory: "barInventory",
            done: false,
            billId: 2,
        },
    ],
    bills: [
        {
            id: 1,
            type: "single",
            vipAccount: false,
            timestamp: "2022-02-18T12:46:13Z",
            amountSEK: 40,
        },
        {
            id: 2,
            type: "split",
            split: 4,
            vipAccount: false,
            timestamp: "2022-02-18T12:46:13Z",
            amountSEK: 160,
        },
    ],
    tannins: ["291702", "2231601", "1217401", "1202501"],
    allergies: [
        {
            name: "sulfite",
            beverages: [
                "192601",
                "192701",
                "291702",
                "1101402",
                "196202",
                "181214",
                "184914",
                "8642507",
                "2231601",
                "1217401",
            ],
        },
        {
            name: "gluten",
            beverages: ["192201"],
        },
        {
            name: "milk",
            beverages: ["68301", "76501", "75902"],
        },
        {
            name: "nuts",
            beverages: ["7112102"],
        },
    ],
    barInventory: [
        {
            beverageNr: "190201",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "190715",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "191801",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "120003",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "192201",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "192401",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "192601",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "192701",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "8115706",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "291702",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "157612",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1101402",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1101502",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "196202",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "181214",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "184914",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1104803",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1105603",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1105703",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1108501",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1160401",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "71002",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "68301",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "76501",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "75902",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "76901",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "8642507",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1012601",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1041301",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1104903",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "10401",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "74901",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "76002",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1174603",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "1202501",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "76201",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "2022701",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "8513101",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "8505701",
            quantity: 42,
            active: true,
        },
        {
            beverageNr: "8507802",
            quantity: 5,
            active: true,
        },
        {
            beverageNr: "8568201",
            quantity: 4,
            active: true,
        },
        {
            beverageNr: "4040602",
            quantity: 5,
            active: true,
        },
        {
            beverageNr: "8115806",
            quantity: 6,
            active: true,
        },
        {
            beverageNr: "8776802",
            quantity: 6,
            active: true,
        },
        {
            beverageNr: "8691202",
            quantity: 6,
            active: true,
        },
        {
            beverageNr: "8773101",
            quantity: 6,
            active: true,
        },
        {
            beverageNr: "7112102",
            quantity: 6,
            active: true,
        },
        {
            beverageNr: "2231601",
            quantity: 6,
            active: true,
        },
        {
            beverageNr: "1217401",
            quantity: 6,
            active: true,
        },
    ],
    vipInventory: [
        {
            beverageNr: "190715",
            quantity: 12,
            active: true,
        },
        {
            beverageNr: "120003",
            quantity: 4,
            active: true,
        },
        {
            beverageNr: "1101402",
            quantity: 20,
            active: true,
        },
        {
            beverageNr: "157612",
            quantity: 2,
            active: true,
        },
        {
            beverageNr: "1105703",
            quantity: 14,
            active: true,
        },
        {
            beverageNr: "1160401",
            quantity: 8,
            active: true,
        },
    ],
    hideFromMenu: ["8642507"],
};
