/*
The provided beverages database is too huge. We should create a new beverages database that only contains 40-60 different items.

Hints from Lars:

Note that the JSON-structure is loaded into a variable in the beginning.
The beverage number is unique, and can serve as an identifying key.
We want to have at least the following characteristics in the beverages database:

alcoholfree beverages
at least one beer with much alcohol
wines with tannin and without tannin
different beer types: IPA, lager, ...
beverages that are relevant for allergies (e.g. gluten, lactose)
some cocktails / drinks
*/

var BeveragesDB =
{
    alcohols:
    [
        {
            nr: "190201",
            articleid: "597009",
            articletype: "1902",
            name: "Raml\u00c3\u00b6sa",
            name2: "",
            priceinclvat: "18.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2011-10-01",
            finaldelivery: " ",
            category: "Alkoholfritt, Vatten",
            packaging: "PET-flaska",
            captype: "Plastkork/syntetkork",
            countryoforigin:
                "Sk\u00c3\u00a5ne l\u00c3\u00a4n, Helsingborgs stad",
            countryoforiginlandname: "Sverige",
            producer: "AB Raml\u00c3\u00b6sa H\u00c3\u00a4lsobrunn",
            provider: "Carlsberg Sverige AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "190715",
            articleid: "622011",
            articletype: "1907",
            name: "San Miguel",
            name2: "0,0 %",
            priceinclvat: "7.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-04-02",
            finaldelivery: " ",
            category: "Alkoholfritt, \u00c3\u2013l",
            packaging: "Burk",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Spanien",
            producer: "San Miguel",
            provider: "Brewery International Sweden A",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "191801",
            articleid: "23196",
            articletype: "1918",
            name: "Mousserande Jordgubbsdryck",
            name2: "Alkoholfri",
            priceinclvat: "33.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2000-05-08",
            finaldelivery: " ",
            category: "Alkoholfritt, Mousserande",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "\u00c3\u2013sterrike",
            producer: "Schloss Raggendorf",
            provider: "Nigab",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "192003",
            articleid: "720171",
            articletype: "1920",
            name: "Xide Non Alco",
            name2: "Lemon Dragonfruit",
            priceinclvat: "13.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-04-02",
            finaldelivery: " ",
            category: "Alkoholfritt, \u00c3\u2013vrigt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "Hallands l\u00c3\u00a4n, Falkenbergs kommun",
            countryoforiginlandname: "Sverige",
            producer: "Carlsberg Sverige AB",
            provider: "Carlsberg Sverige AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.5%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "192201",
            articleid: "339014",
            articletype: "1922",
            name: "Weihenstephaner",
            name2: "Hefeweissbier Alkoholfrei",
            priceinclvat: "12.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2008-10-01",
            finaldelivery: " ",
            category: "Alkoholfritt, \u00c3\u2013l",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Tyskland",
            producer: "Weihenstephan",
            provider: "Galatea Spirits AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.4%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "192401",
            articleid: "547848",
            articletype: "1924",
            name: "Stirrings",
            name2: "Simple Mojito",
            priceinclvat: "63.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2011-04-01",
            finaldelivery: " ",
            category: "Alkoholfritt, Aperitif och Bit",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "USA",
            producer: "Stirring",
            provider: "Diageo Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.3%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "192502",
            articleid: "681767",
            articletype: "1925",
            name: "Nigrum",
            name2: "",
            priceinclvat: "35.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-10-01",
            finaldelivery: " ",
            category: "Alkoholfritt, Must",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "Sverige",
            producer: "Ribes Nigrum Ving\u00c3\u00a5rd",
            provider: "Ribes Nigrum Ving\u00c3\u00a5rd AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.5%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "192601",
            articleid: "345699",
            articletype: "1926",
            name: "Chapel Hill",
            name2: "Sparkling Collection Doux",
            priceinclvat: "42.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2008-11-03",
            finaldelivery: " ",
            category: "Alkoholfritt, Mousserande",
            packaging: "Flaska",
            captype: "Plastkork/syntetkork",
            countryoforigin: "",
            countryoforiginlandname: "Ungern",
            producer: "Balatonbogl\u00c3\u00a1r Winery",
            provider: "Henkell & Co Sverige AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.1%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "192701",
            articleid: "583145",
            articletype: "1927",
            name: "Isabella Spagnolo",
            name2: "Isabella Ice",
            priceinclvat: "49.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2011-11-14",
            finaldelivery: " ",
            category: "Alkoholfritt, Mousserande",
            packaging: "Flaska",
            captype: "Naturkork",
            countryoforigin: "",
            countryoforiginlandname: "Italien",
            producer: "Azienda Iris",
            provider: "The Wine Team",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0%",
            module: "",
            assortment: "TSV",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "196303",
            articleid: "621936",
            articletype: "1963",
            name: "Fentimans",
            name2: "Ginger Beer",
            priceinclvat: "22.50",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-04-02",
            finaldelivery: " ",
            category: "Alkoholfritt, \u00c3\u2013vrigt",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "Storbritannien",
            producer: "Fentimans",
            provider: "Bonasitis AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.5%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "291702",
            articleid: "45565",
            articletype: "2917",
            name: "PMC",
            name2: "Beerenauslese Cuv\u00c3\u00a9e",
            priceinclvat: "80.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2004-02-02",
            finaldelivery: " ",
            category: "Vitt vin, S\u00c3\u00b6tt",
            packaging: "Flaska",
            captype: "Naturkork",
            countryoforigin: "Burgenland",
            countryoforiginlandname: "\u00c3\u2013sterrike",
            producer: "Weingut PMC",
            provider: "Edrington Sweden AB",
            productionyear: "2008",
            testedproductionyear: "2008",
            alcoholstrength: "11%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "157612",
            articleid: "509166",
            articletype: "1576",
            name: "Abbot Ale",
            name2: "",
            priceinclvat: "17.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2011-11-22",
            finaldelivery: " ",
            category: "\u00c3\u2013l, Ale",
            packaging: "Burk",
            captype: "",
            countryoforigin: "England",
            countryoforiginlandname: "Storbritannien",
            producer: "Greene King",
            provider: "TOMP Beer Wine & Spirits AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "5%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1101402",
            articleid: "667609",
            articletype: "11014",
            name: "Briska",
            name2: "Vinter \u00c3\u201epple & Kanel",
            priceinclvat: "15.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-11-15",
            finaldelivery: " ",
            category: "Cider, S\u00c3\u00b6t",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Sverige",
            producer: "Spendrups",
            provider: "Spendrups Bryggeri AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "4.5%",
            module: "",
            assortment: "TSS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1101502",
            articleid: "667645",
            articletype: "11015",
            name: "Xide Winter",
            name2: "Tangelo & Ginger",
            priceinclvat: "17.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-11-15",
            finaldelivery: " ",
            category: "Blanddrycker",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "Kronobergs l\u00c3\u00a4n, Tingsryds kommun",
            countryoforiginlandname: "Sverige",
            producer: "Carlsberg Sverige AB",
            provider: "Carlsberg Sverige AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "4.5%",
            module: "",
            assortment: "TSS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "196202",
            articleid: "629050",
            articletype: "1962",
            name: "Briska",
            name2: "P\u00c3\u00a4ron",
            priceinclvat: "10.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-04-02",
            finaldelivery: " ",
            category: "Alkoholfritt, Cider",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "Dalarnas l\u00c3\u00a4n, Ludvika kommun",
            countryoforiginlandname: "Sverige",
            producer: "Spendrups",
            provider: "Spendrups Bryggeri AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.3%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "196303",
            articleid: "621936",
            articletype: "1963",
            name: "Fentimans",
            name2: "Ginger Beer",
            priceinclvat: "22.50",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-04-02",
            finaldelivery: " ",
            category: "Alkoholfritt, \u00c3\u2013vrigt",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "Storbritannien",
            producer: "Fentimans",
            provider: "Bonasitis AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "0.5%",
            module: "",
            assortment: "FS\u00c3\u2013",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "181214",
            articleid: "850721",
            articletype: "1812",
            name: "Briska",
            name2: "Fl\u00c3\u00a4der",
            priceinclvat: "12.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2014-09-01",
            finaldelivery: " ",
            category: "Cider, S\u00c3\u00b6t",
            packaging: "Burk",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Sverige",
            producer: "Hellefors Bryggeri",
            provider: "Spendrups Bryggeri AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "4.5%",
            module: "",
            assortment: "FSN",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "184914",
            articleid: "779896",
            articletype: "1849",
            name: "Briska",
            name2: "P\u00c3\u00a4ron & Vanilj",
            priceinclvat: "13.20",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-12-02",
            finaldelivery: " ",
            category: "Cider, S\u00c3\u00b6t",
            packaging: "Burk",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Sverige",
            producer: "Spendrups",
            provider: "Spendrups Bryggeri AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "4.5%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1104803",
            articleid: "722671",
            articletype: "11048",
            name: "Suruga Bay",
            name2: "Imperial IPA",
            priceinclvat: "59.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-04-02",
            finaldelivery: " ",
            category: "\u00c3\u2013l, Ale",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Japan",
            producer: "Baird Brewing Co",
            provider: "Cask Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "7.5%",
            module: "T7",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1105603",
            articleid: "723541",
            articletype: "11056",
            name: "Vuur & Vlam",
            name2: "IPA",
            priceinclvat: "26.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-02-01",
            finaldelivery: " ",
            category: "\u00c3\u2013l, Ale",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Nederl\u00c3\u00a4nderna",
            producer: "Brouwerij De Molen",
            provider: "Galatea Spirits AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "6.2%",
            module: "T5",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },{
            nr: "1105703",
            articleid: "723902",
            articletype: "11057",
            name: "Stronzo",
            name2: "Swagger Juze",
            priceinclvat: "46.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-03-01",
            finaldelivery: " ",
            category: "\u00c3\u2013l, Porter och Stout",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Danmark",
            producer: "Stronzo Brewing Co",
            provider: "Elixir HB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "8%",
            module: "",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1108501",
            articleid: "736764",
            articletype: "11085",
            name: "Stiegl Double IPA",
            name2: "",
            priceinclvat: "109.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-04-02",
            finaldelivery: " ",
            category: "\u00c3\u2013l, Ale",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "\u00c3\u2013sterrike",
            producer: "Stiegl brauerei",
            provider: "Galatea Spirits AB",
            productionyear: "2012",
            testedproductionyear: "",
            alcoholstrength: "9.2%",
            module: "T7",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1160401",
            articleid: "655471",
            articletype: "11604",
            name: "Stone 16th Anniversary",
            name2: "IPA",
            priceinclvat: "98.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-12-01",
            finaldelivery: " ",
            category: "\u00c3\u2013l, Ale",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "USA",
            producer: "The Stone Brewing Co",
            provider: "Great Brands AB",
            productionyear: "2012",
            testedproductionyear: "",
            alcoholstrength: "10%",
            module: "T5",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "71002",
            articleid: "14946",
            articletype: "710",
            name: "Malibu",
            name2: "",
            priceinclvat: "150.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "1998-03-02",
            finaldelivery: " ",
            category: "Lik\u00c3\u00b6r, Choklad-, kaffe- och n",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Storbritannien",
            producer: "Malibu",
            provider: "Pernod Ricard Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "21%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "68301",
            articleid: "400688",
            articletype: "683",
            name: "Baileys",
            name2: "Coffee",
            priceinclvat: "199.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2009-10-01",
            finaldelivery: " ",
            category: "Lik\u00c3\u00b6r, Gr\u00c3\u00a4dde och \u00c3\u00a4gg",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "Irland",
            producer: "Baileys Global Supply",
            provider: "Diageo Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "17%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "76501",
            articleid: "25936",
            articletype: "765",
            name: "Baileys",
            name2: "Original Irish Cream",
            priceinclvat: "199.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2000-09-04",
            finaldelivery: " ",
            category: "Lik\u00c3\u00b6r, Gr\u00c3\u00a4dde och \u00c3\u00a4gg",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "Irland",
            producer: "Baileys Global Supply",
            provider: "Diageo Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "17%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "75902",
            articleid: "779891",
            articletype: "759",
            name: "Baileys",
            name2: "Chocolat Luxe",
            priceinclvat: "199.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-12-02",
            finaldelivery: " ",
            category: "Lik\u00c3\u00b6r, Gr\u00c3\u00a4dde och \u00c3\u00a4gg",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Irland",
            producer: "Diageo Plc",
            provider: "Diageo Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "15.7%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "76901",
            articleid: "429329",
            articletype: "769",
            name: "Bacardi",
            name2: "Mojito Classic",
            priceinclvat: "130.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2010-03-24",
            finaldelivery: " ",
            category: "Drinkar och Cocktails",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "Internationellt m\u00c3\u00a4rke",
            producer: "Bacardi",
            provider: "Bacardi AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "14.9%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8642507",
            articleid: "653021",
            articletype: "86425",
            name: "Raspberry",
            name2: "Mojito",
            priceinclvat: "189.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-04-02",
            finaldelivery: " ",
            category: "Drinkar och Cocktails",
            packaging: "Box",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Sverige",
            producer: "Svensk Export Vodka AB",
            provider: "Fondberg",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "12.5%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1012601",
            articleid: "874805",
            articletype: "10126",
            name: "Nikka Taketsuru",
            name2: "Pure Malt",
            priceinclvat: "549.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2014-10-03",
            finaldelivery: " ",
            category: "Whisky, Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Japan",
            producer: "The Nikka Whisky Distilling Co",
            provider: "Symposion International AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "43%",
            module: "",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1041301",
            articleid: "304394",
            articletype: "10413",
            name: "Nikka Yoichi",
            name2: "Single Malt 10 Years",
            priceinclvat: "599.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2008-04-01",
            finaldelivery: " ",
            category: "Whisky, Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Japan",
            producer: "The Nikka Whisky Distilling Co",
            provider: "Symposion International AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "45%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1104903",
            articleid: "722706",
            articletype: "11049",
            name: "Rising Sun",
            name2: "Pale Ale",
            priceinclvat: "59.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-04-02",
            finaldelivery: " ",
            category: "\u00c3\u2013l, Ale",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Japan",
            producer: "Baird Brewing Co",
            provider: "Cask Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "5%",
            module: "",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "10401",
            articleid: "181",
            articletype: "104",
            name: "Gekkeikan Sake",
            name2: "",
            priceinclvat: "89.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "1993-01-24",
            finaldelivery: " ",
            category: "Sake",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "USA",
            producer: "Gekkeikan",
            provider: "Bornicon & Salming",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "14.6%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "74901",
            articleid: "27460",
            articletype: "749",
            name: "J\u00c3\u00a4germeister",
            name2: "",
            priceinclvat: "259.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2001-01-02",
            finaldelivery: " ",
            category: "Lik\u00c3\u00b6r, Kryddor och \u00c3\u00b6rter",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Tyskland",
            producer: "W Mast",
            provider: "Berntson Brands AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "35%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "76002",
            articleid: "301129",
            articletype: "760",
            name: "Bols",
            name2: "Coffee",
            priceinclvat: "139.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2008-04-01",
            finaldelivery: " ",
            category: "Lik\u00c3\u00b6r, Choklad-, kaffe- och n",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Nederl\u00c3\u00a4nderna",
            producer: "Bols",
            provider: "Edrington Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "24%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1174603",
            articleid: "676201",
            articletype: "11746",
            name: "Samichlaus Bier",
            name2: "",
            priceinclvat: "41.90",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-12-01",
            finaldelivery: " ",
            category: "\u00c3\u2013l, M\u00c3\u00b6rk lager",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "\u00c3\u2013sterrike",
            producer: "Brauerei Schloss Eggenberger",
            provider: "World Beer Trading KB",
            productionyear: "2012",
            testedproductionyear: "",
            alcoholstrength: "14%",
            module: "T5",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1202501",
            articleid: "31542",
            articletype: "12025",
            name: "Lemon Gold",
            name2: "Citron",
            priceinclvat: "62.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2001-11-05",
            finaldelivery: " ",
            category: "Smaksatt vin",
            packaging: "Papp",
            captype: "",
            countryoforigin:
                "Sk\u00c3\u00a5ne l\u00c3\u00a4n, Simrishamns kommun",
            countryoforiginlandname: "Sverige",
            producer: "\u00c3\u2026kesson Vin AB",
            provider: "Kiviks Musteri AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "15%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "76201",
            articleid: "25434",
            articletype: "762",
            name: "P\u00c3\u00a8re Kermann's Absinthe",
            name2: "",
            priceinclvat: "386.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2000-09-04",
            finaldelivery: " ",
            category: "Aniskryddad sprit",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "",
            countryoforiginlandname: "Frankrike",
            producer: "Slaur",
            provider: "Juvinum Food & Beverage AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "60%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "2022701",
            articleid: "586992",
            articletype: "20227",
            name: "Bowmore",
            name2: "Liquid Library 12 Years",
            priceinclvat: "749.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2011-09-01",
            finaldelivery: " ",
            category: "Whisky , Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "Skottland, Islay",
            countryoforiginlandname: "Storbritannien",
            producer: "The Whisky Agency",
            provider: "Origo Wine Import",
            productionyear: "1998",
            testedproductionyear: "",
            alcoholstrength: "61.8%",
            module: "T7",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8513101",
            articleid: "623444",
            articletype: "85131",
            name: "Miltonduff",
            name2: "13 Years",
            priceinclvat: "819.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2011-12-01",
            finaldelivery: " ",
            category: "Whisky, Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "Skottland, Highlands, Speyside",
            countryoforiginlandname: "Storbritannien",
            producer: "The Riverstown Whisky Company",
            provider: "Clydesdale AB",
            productionyear: "1998",
            testedproductionyear: "",
            alcoholstrength: "61.4%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8505701",
            articleid: "861914",
            articletype: "85057",
            name: "Ledaig",
            name2: "Raw Cask Sherry Butt 16 Years",
            priceinclvat: "1070.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2014-07-01",
            finaldelivery: " ",
            category: "Whisky, Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "Skottland, Highlands, Islands, Isle of M",
            countryoforiginlandname: "Storbritannien",
            producer: "Blackadder",
            provider: "Clydesdale AB",
            productionyear: "1998",
            testedproductionyear: "",
            alcoholstrength: "62.2%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8507802",
            articleid: "661370",
            articletype: "85078",
            name: "Tormore 21y 90",
            name2: "Bourbon Barrel 21 Years",
            priceinclvat: "1292.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-05-02",
            finaldelivery: " ",
            category: "Whisky, Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "Skottland, Highlands, Speyside",
            countryoforiginlandname: "Storbritannien",
            producer: "Auld Rare Whisky Sweden",
            provider: "Auld Rare Whisky Sweden AB",
            productionyear: "1990",
            testedproductionyear: "",
            alcoholstrength: "62.4%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8568201",
            articleid: "701443",
            articletype: "85682",
            name: "Amrut Peated",
            name2: "Raw Cask",
            priceinclvat: "948.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-10-01",
            finaldelivery: " ",
            category: "Whisky, Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Indien",
            producer: "Blackadder",
            provider: "Clydesdale AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "62.7%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "4040602",
            articleid: "816788",
            articletype: "40406",
            name: "Sm\u00c3\u00b6gen Prim\u00c3\u00b6r",
            name2: "",
            priceinclvat: "1276.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2014-03-13",
            finaldelivery: " ",
            category: "Whisky, Malt",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Sverige",
            producer: "Sm\u00c3\u00b6gen Whisky AB",
            provider: "Sm\u00c3\u00b6gen Whisky AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "63.7%",
            module: "",
            assortment: "TSE",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8623801",
            articleid: "701766",
            articletype: "86238",
            name: "Grande Absente",
            name2: "",
            priceinclvat: "502.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-10-01",
            finaldelivery: " ",
            category: "\u00c3\u2013vrig sprit",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Frankrike",
            producer: "Distilleries et Domaines de Pr",
            provider: "AB Wicked Wine Sweden",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "69%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8776802",
            articleid: "845759",
            articletype: "87768",
            name: "Gr\u00c3\u00b6n Opal",
            name2: "Absinthe",
            priceinclvat: "542.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2014-05-02",
            finaldelivery: " ",
            category: "Aniskryddad sprit",
            packaging: "Flaska",
            captype: "",
            countryoforigin:
                "\u00c3\u2013rebro l\u00c3\u00a4n, \u00c3\u2013rebro kommun",
            countryoforiginlandname: "Sverige",
            producer: "Svensk Absint AB",
            provider: "Svensk Absint AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "72%",
            module: "",
            assortment: "TSLS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8691202",
            articleid: "643989",
            articletype: "86912",
            name: "Tabu",
            name2: "Classic Strong Absinth",
            priceinclvat: "666.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2012-02-01",
            finaldelivery: " ",
            category: "Aniskryddad sprit",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Tyskland",
            producer: "Felix Rauter",
            provider: "Renbjer & Magnusson AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "73%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "8773101",
            articleid: "748275",
            articletype: "87731",
            name: "Tilambic 151",
            name2: "Overproof Rum",
            priceinclvat: "802.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2013-04-02",
            finaldelivery: " ",
            category: "Rom, M\u00c3\u00b6rk",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Mauritius",
            producer: "Green Island",
            provider: "Whiskytaste Sweden AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "75.5%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "7112102",
            articleid: "189918",
            articletype: "71121",
            name: "Amaretto",
            name2: "",
            priceinclvat: "195.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2006-01-02",
            finaldelivery: " ",
            category: "Lik\u00c3\u00b6r, Choklad-, kaffe- och n",
            packaging: "Flaska",
            captype: "",
            countryoforigin: "",
            countryoforiginlandname: "Frankrike",
            producer: "Cartron",
            provider: "Fondberg",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "25%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "2231601",
            articleid: "13932",
            articletype: "22316",
            name: "Pater Sangiovese",
            name2: "",
            priceinclvat: "75.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "1997-10-06",
            finaldelivery: " ",
            category: "R\u00c3\u00b6tt vin, Kryddigt & Mustigt",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "Toscana",
            countryoforiginlandname: "Italien",
            producer: "Frescobaldi",
            provider: "Spendrups Bryggeri AB",
            productionyear: "",
            testedproductionyear: "",
            alcoholstrength: "12.5%",
            module: "",
            assortment: "BS",
            organic: "0",
            kosher: "0",
        },
        {
            nr: "1217401",
            articleid: "190669",
            articletype: "12174",
            name: "Hidden Rock",
            name2: "Petit Verdot Cabernet Sauvignon",
            priceinclvat: "59.00",
            volumeml: null,
            priceperlitre: null,
            introduced: "2006-04-01",
            finaldelivery: " ",
            category: "R\u00c3\u00b6tt vin, Fruktigt & Smakrikt",
            packaging: "Flaska",
            captype: "Skruvkapsyl",
            countryoforigin: "South Eastern Australia",
            countryoforiginlandname: "Australien",
            producer: "Dominic Wines",
            provider: "Enjoy Wine & Spirits AB",
            productionyear: "2013",
            testedproductionyear: "2013",
            alcoholstrength: "13.5%",
            module: "",
            assortment: "FS",
            organic: "0",
            kosher: "0",
        },
    ]
};
